### ISSUE TITLE
Install via package manager?

### ISSUE THREAD

**Issue by lesnyrysiek** [Codenator81/modxTwigTemplateEngine#1]
The repository "http://codenator.dev-point.org/extras/" providet thet forums doesn't work.
Is there only way to install it just by copy pasting?

**Comment by Codenator81** [comment]
http://modx.com/extras/package/modxtwigtemplateengine   link to Manager
Package name modxTwig in package manager

**Comment by Codenator81** [comment]
If u need another template better try Smarty from filosof. I do it as experiment but find out Smarty more comfortable to work on MODX

**Comment by lesnyrysiek** [comment]
Found it! Thanks!

**Comment by Codenator81** [comment]
Really I integrate Symfony with MODX that way I do this module
Using MODX as admin panel
